
package nl.logius.digipoort.wus._2_0.statusinformatieservice._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatusinformatieService_V1_2", targetNamespace = "http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/", wsdlLocation = "file:/your/location/example-java-biv-connector/src/main/resources/wsdl/Statusinformatieservice_WUS20v12_prod.wsdl")
public class StatusinformatieServiceV12_Service
    extends Service
{

    private final static URL STATUSINFORMATIESERVICEV12_WSDL_LOCATION;
    private final static WebServiceException STATUSINFORMATIESERVICEV12_EXCEPTION;
    private final static QName STATUSINFORMATIESERVICEV12_QNAME = new QName("http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/", "StatusinformatieService_V1_2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/your/location/example-java-biv-connector/src/main/resources/wsdl/Statusinformatieservice_WUS20v12_prod.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATUSINFORMATIESERVICEV12_WSDL_LOCATION = url;
        STATUSINFORMATIESERVICEV12_EXCEPTION = e;
    }

    public StatusinformatieServiceV12_Service() {
        super(__getWsdlLocation(), STATUSINFORMATIESERVICEV12_QNAME);
    }

    public StatusinformatieServiceV12_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATUSINFORMATIESERVICEV12_QNAME, features);
    }

    public StatusinformatieServiceV12_Service(URL wsdlLocation) {
        super(wsdlLocation, STATUSINFORMATIESERVICEV12_QNAME);
    }

    public StatusinformatieServiceV12_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATUSINFORMATIESERVICEV12_QNAME, features);
    }

    public StatusinformatieServiceV12_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatusinformatieServiceV12_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatusinformatieServiceV12
     */
    @WebEndpoint(name = "StatusinformatieService_V1_2")
    public StatusinformatieServiceV12 getStatusinformatieServiceV12() {
        return super.getPort(new QName("http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/", "StatusinformatieService_V1_2"), StatusinformatieServiceV12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatusinformatieServiceV12
     */
    @WebEndpoint(name = "StatusinformatieService_V1_2")
    public StatusinformatieServiceV12 getStatusinformatieServiceV12(WebServiceFeature... features) {
        return super.getPort(new QName("http://logius.nl/digipoort/wus/2.0/statusinformatieservice/1.2/", "StatusinformatieService_V1_2"), StatusinformatieServiceV12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATUSINFORMATIESERVICEV12_EXCEPTION!= null) {
            throw STATUSINFORMATIESERVICEV12_EXCEPTION;
        }
        return STATUSINFORMATIESERVICEV12_WSDL_LOCATION;
    }

}
