
package nl.logius.digipoort.wus._2_0.aanleverservice._1;

import javax.xml.ws.WebFault;
import nl.logius.digipoort.koppelvlakservices._1.FoutType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "aanleverFault", targetNamespace = "http://logius.nl/digipoort/koppelvlakservices/1.2/")
public class AanleverServiceFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FoutType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AanleverServiceFault(String message, FoutType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AanleverServiceFault(String message, FoutType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: nl.logius.digipoort.koppelvlakservices._1.FoutType
     */
    public FoutType getFaultInfo() {
        return faultInfo;
    }

}
